image: europe-docker.pkg.dev/gitpod-artifacts/docker-dev/workspace-full:2022-01-27-08-27-20
tasks:
- init: ./mvnw package -DskipTests
  command: java -jar target/*.jar

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
